"""add game_xp_today and game_xp_date to user_stats

Revision ID: c88f64ed817a
Revises: 782e9ac7ad12
Create Date: 2026-06-11 12:17:26.371535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88f64ed817a'
down_revision = '782e9ac7ad12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_xp_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('game_xp_date', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_stats', schema=None) as batch_op:
        batch_op.drop_column('game_xp_date')
        batch_op.drop_column('game_xp_today')

    # ### end Alembic commands ###
