"""add role and stripe fields to users

Revision ID: d4f19b2e8a10
Revises: 5b0743a9e864
Create Date: 2026-10-03 22:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f19b2e8a10'
down_revision = '5b0743a9e864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), server_default='student', nullable=False))
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('stripe_plan_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=50), server_default='free', nullable=True))
        batch_op.add_column(sa.Column('current_period_end', sa.DateTime(), nullable=True))
        batch_op.create_index('ix_users_stripe_customer_id', ['stripe_customer_id'], unique=True)
        batch_op.create_index('ix_users_stripe_subscription_id', ['stripe_subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_stripe_subscription_id')
        batch_op.drop_index('ix_users_stripe_customer_id')
        batch_op.drop_column('current_period_end')
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_plan_id')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')
        batch_op.drop_column('role')
    # ### end Alembic commands ###
